export interface IMenuItem {
    primeicon?:string,
    secondicon?:string,
    label: string,
    to: string,
    Type: number,
    MenuPermission?: any
    UseForList?:boolean
  }

var MenuPermission={
    'Create':false,
    'View':false,
    'Edit':false,
    'Delete':false
}

const data: IMenuItem[] = [
    {
        primeicon:'home-black.svg',
        secondicon:'home-white.svg',
        label:'Dashboard',
        to:'dashboard',
        Type: 1,
        UseForList:true,      
    },
    {
        primeicon:'ticket-central-black.svg',
        secondicon:'ticket-central-white.svg',
        label:'Ticket Central',
        to:'lab',
        Type: 2,
        UseForList:true,
    },
    {
        label:'Ticket Resolution Center',
        to:'ticket-resolution',
        Type: 3,
        UseForList:true,
    },
    {
        label:'Complaints',
        to:'lab',
        Type: 4,
        UseForList:false,
    },
    {
        label:'Create Customer Service Complaints',
        to:'ticketcentral/Complaints',
        Type: 4,
        UseForList:true,
    },
    {
        label:'IT/EMR Issues',
        to:'lab',
        Type: 5,
        UseForList:false,
    },
    {
        label:'Create Customer Service IT/EMR Issues',
        to:'ticketcentral/IT-EMR',
        Type: 5,
        UseForList:true,
    },
    {
        label:'Client Billing/Account Billing Ticket',
        to:'lab',
        Type: 6,
        UseForList:false,
    },
    {
        label:'Create Customer Service Client Billing/Account Billing Ticket',
        to:'ticketcentral/Client&Account',
        Type: 6,
        UseForList:true,
    },
    {
        label:'Patient Question',
        to:'lab',
        Type: 7,
        UseForList:false,
    },
    {
        label:'Create Customer Service Patient Question',
        to:'ticketcentral/Patient',
        Type: 7,
        UseForList:true,
    },
    {
        label:'Sales Calls',
        to:'lab',
        Type: 8,
        UseForList:false,
    },
    {
        label:'Create Customer Service Sales Calls',
        to:'ticketcentral/Sales',
        Type: 8,
        UseForList:true,
    },
    {
        label:'National Calls',
        to:'lab',
        Type: 9,
        UseForList:false,
    },
    {
        label:'Create Customer Service National Calls',
        to:'ticketcentral/National',
        Type: 9,
        UseForList:true,
    },
    {
        label:'Centrifuge Issues',
        to:'lab',
        Type: 10,
        UseForList:false,
    },
    {
        label:'Create Customer Service Centrifuge Issues',
        to:'ticketcentral/Centrifuge',
        Type: 10,
        UseForList:true,
    },
    {
        label:'Lab Technical Questions',
        to:'lab',
        Type: 11,
        UseForList:false,
    },
    {
        label:'Create Customer Service Lab Technical Questions',
        to:'ticketcentral/Technical',
        Type: 11,
        UseForList:true,
    },
    {
        label:'Sales Tickets',
        to:'lab',
        Type: 12,
        UseForList:true,
    },
    {
        label:'EMR Request',
        to:'lab',
        Type: 13,
        UseForList:false,        
    },
    {
        label:'Create Sales EMR Request',
        to:'ticket/sales-emr',
        Type: 13,
        UseForList:true,        
    },
    {
        label:'COMP Request',
        to:'lab',
        Type: 14,
        UseForList:false,
    },
    {
        label:'Create Sales COMP Request',
        to:'ticketcentral/COMP',
        Type: 14,
        UseForList:true,
    },
    {
        primeicon:'requisition-central-black.svg',
        secondicon:'requisition-central-white.svg',
        label:'Requistion Central',
        to:'lab',
        Type: 15,
        UseForList:true,       
    },
    {
        label:'Covid-19 Req Forms',
        to:'covid19-req-orders',
        Type: 16,
        UseForList:true,
    },
    {
        label:'Covid-19 Surveys',
        to:'lab',
        Type: 17,
        UseForList:true,
    },
    {
        primeicon:'rejected-specimens-black.svg',
        secondicon:'rejected-specimens-white.svg',
        label:'Rejected Specimens',
        to:'rejected-specimens',
        Type: 18,   
        UseForList:true,
    },
    {
        primeicon:'addon-tests-black.svg',
        secondicon:'addon-tests-white.svg',
        label:'Addon Tests',
        to:'add-on-test',
        Type: 19,
        UseForList:true,
    },
    {
        primeicon:'update-pt-info-black.svg',
        secondicon:'update-pt-info-white.svg',
        label:'Update Pt. Info',
        to:'patient-info',
        Type: 20,
        UseForList:true,
    },
    {
        primeicon:'ups-pickup-black.svg',
        secondicon:'ups-pickup-white.svg',
        label:'UPS Pickup',
        to:'ups-pickup',
        Type: 21,
        UseForList:true,
    },
    {
        primeicon:'logistic-central-black.svg',
        secondicon:'logistic-central-white.svg',
        label:'Logistic Central',
        to:'lab',
        Type: 22,
        UseForList:true,
    },
    {
        label:'National Supply Orders',
        to:'logistic-central/national-order',
        Type: 23,
        UseForList:true,
    },
    // {
    //     label:'Create National Supply Orders',
    //     to:'lab',
    //     Type: 23,
    //     UseForList:true,
    // },
    {
        label:'Covid-19 Orders',
        to:'logistic-central/covid19-order',
        Type: 24,
        UseForList:true,
    },
    {
        label:'At-Home SalivaDirect',
        to:'logistic-central/salivadirect-order',
        Type: 25,
        UseForList:true,
    },
    {
        label:'Non-Covid19 Orders',
        to:'logistic-central/noncovid-order',
        Type: 26,
        UseForList:true,
    },
    {
        label:'CLS Orders',
        to:'logistic-central/cls-order',
        Type: 27,
        UseForList:true,
    },
    {
        label:'Kits Orders',
        to:'logistic-central/kit-order',
        Type: 28,
        UseForList:true,
    },
    {
        label:'Kits Sold',
        to:'logistic-central/kit-sold',
        Type: 29,
        UseForList:true,
    },
    {
        primeicon:'follow-up-black.svg',
        secondicon:'follow-up-white.svg',
        label:'Follow Up',
        to:'lab',
        Type: 30,
        UseForList:true,
    },
    {
        label:'Resolution Center',
        to:'follow-up/resolution-center',
        Type: 31,
        UseForList:true,
    },
    {
        primeicon:'requisition-central-black.svg',
        secondicon:'requisition-central-white.svg',
        label:'EMR Central',
        to:'emr-central',
        Type: 48,
        UseForList:true,
    },
    // {
    //     label:'EMR Central',
    //     to:'emr-central',
    //     Type: 48,
    //     UseForList:false,
    // },
    
    // {
    //     primeicon:'requisition-central-black.svg',
    //     secondicon:'requisition-central-white.svg',
    //     label:'Returned/Discarded Specimen Log',
    //     to:'follow-up/discard-specimen',
    //     Type: 34,
    //     UseForList:true,
    // },
    // {
    //     label:'Create Returned/Discarded Specimen Log',
    //     to:'lab',
    //     Type: 34,
    //     UseForList:true,
    // },
    {
        label:'Accession Follow Up',
        to:'lab',
        Type: 32,
        UseForList:false,
    },
    {
        label:'Create Accession Follow Up',
        to:'follow-up/new-accession',
        Type: 32,
        UseForList:true,
    },
    {
        label:'Accession Add-On/Correction',
        to:'lab',
        Type: 33,
        UseForList:false,
    },
    {
        label:'Create Accession Add-On/Correction',
        to:'follow-up/add-on',
        Type: 33,
        UseForList:true,
    },
    {
        primeicon:'sales-central-black.svg',
        secondicon:'sales-central-white.svg',
        label:'Sales Central',
        to:'lab',
        Type: 35,
        UseForList:true,
    },
    {
        label:'Sales End Of Day Log History',
        to:'salescentral',
        Type: 57,
        UseForList:true,
    },
    // {
    //     label:'Create Sales End Of Day Log History',
    //     to:'salescentral/create',
    //     Type: 57,
    //     UseForList:true,
    // },
    {
        primeicon:'client-billing-black.svg',
        secondicon:'client-billing-white.svg',
        label:'Client Billing',
        to:'client-billing',
        Type: 36,
        UseForList:true,
    },
    {
        primeicon:'account-mgmt-black.svg',
        secondicon:'account-mgmt-white.svg',
        label:'Account MGMT',
        to:'lab',
        Type: 37,
        UseForList:true,
    },
    {
        label:'Email Alert',
        to:'emailalerts',
        Type: 38,
        UseForList:true,
    },
    {
        label:'Manage Shipping',
        to:'shipping',
        Type: 39,
        UseForList:true,
    },
    {
        label:'Manage Product',
        to:'products',
        Type: 40,
        UseForList:true,
    },
    // {
    //     label:'Create Product',
    //     to:'lab',
    //     Type: 40,
    //     UseForList:true,
    // },
    {
        label:'Manage Product Category',
        to:'product-category',
        Type: 41,
        UseForList:true,
    },
    // {
    //     label:'Create Products Category',
    //     to:'lab',
    //     Type: 41,
    //     UseForList:true,
    // },
    {
        label:'Inventory MGMT',
        to:'inventory-mgmt',
        Type: 42,
        UseForList:true,
    },
    {
        label:'New Register',
        to:'lab',
        Type: 43,
        UseForList:true,
    },
    {
        label:'Member Physician',
        to:'memberphysician',
        Type: 44,
        UseForList:true,
    },
    {
        label:'Manage User',
        to:'user',
        Type: 45,
        UseForList:true,
    },
    {
        label:'Manage Department & Permission',
        to:'department',
        Type: 47,
        UseForList:true,
    },
    {
        primeicon:'access-auto-bill-black.svg',
        secondicon:'access-auto-bill-white.svg',
        label:'Access Auto Bill',
        to:'lab',
        Type: 51,
        UseForList:true,
    },
    {
        label:'AGING Report',
        to:'access-auto-bill/aging-report',
        Type: 52,
        UseForList:true,
    },
    {
        label:'Cash Dash',
        to:'access-auto-bill/cash-dash',
        Type: 53,
        UseForList:true,
    },
    {
        label:'Billing Invoices',
        to:'access-auto-bill/billing-invoice',
        Type: 54,
        UseForList:true,
    },
    {
        primeicon:'access-auto-bill-black.svg',
        secondicon:'access-auto-bill-white.svg',
        label:'Billing Cycle',
        to:'access-auto-bill/billing-cycle',
        Type: 55,
        UseForList:true,
    },
    {
        label:'Payment Report',
        to:'access-auto-bill/payment-report',
        Type: 56,
        UseForList:true,
    },
    {
        label:'Recurring Orders',
        to:'logistic-central/recurring-order',
        Type: 66,
        UseForList:true,
    },
    {
        label:'Existing Orders',
        to:'lab',
        Type: 59,
        UseForList:true,
    },
    {
        label:'Create Orders',
        to:'lab',
        Type: 59,
        UseForList:true,
    },
    {
        label:'Archives Orders',
        to:'lab',
        Type: 60,
        UseForList:true,
    },
    {
        primeicon:'ticket-central-black.svg',
        secondicon:'ticket-central-white.svg',
        label:'Delete Duplicate Test',
        to:'follow-up/duplicate-test',
        Type: 61,
        UseForList:true,
    },
    {
        primeicon:'ticket-central-black.svg',
        secondicon:'ticket-central-white.svg',
        label:'Additional Correspondence',
        to:'follow-up/correspondence',
        Type: 62,
        UseForList:true,
    },
    {
        primeicon:'npi-request-black.svg',
        secondicon:'npi-request-white.svg',
        label:'NPI Request',
        to:'npi-request',
        Type: 63,
        UseForList:true,
    },
    // {
    //     primeicon:'ticket-central-black.svg',
    //     secondicon:'ticket-central-white.svg',
    //     label:'Demo',
    //     to:'lab',
    //     Type: 64,
    //     UseForList:true,
    // },
    {
        primeicon:'report-black.svg',
        secondicon:'report-white.svg',
        label:'Report',
        to:'lab',
        Type: 64,
        UseForList:true,
    },
    {
        label:'Credit Card Log',
        to:'reports/creditcard',
        Type: 65,
        UseForList:true,
    },
    {
        label:'Charge Invoice',
        to:'access-auto-bill/charge-invoice',
        Type: 67,
        UseForList:true,
    },
    {   
        primeicon:'webmaster_Black.svg',
        secondicon:'webmaster_White.svg',
        label:'Webmaster',
        to:'lab',
        Type: 68,
        UseForList:true,
    },
    {   label:'Manage Coupons',
        to:'web-master/manage-coupon',
        Type: 69,
        UseForList:true,
    },
    {   label:'Manage Products',
        to:'web-master/manage-products',
        Type: 70,
        UseForList:true,
    },
    {   label:'Test Searches',
        to:'web-master/test-searches',
        Type: 71,
        UseForList:true,
    },
    {   label:'CMS',
        to:'lab',
        Type: 72,
        UseForList:true,
    },
    {   label:'Manage News',
        to:'web-master/manage-news',
        Type: 73,
        UseForList:true,
    },
    {   label:'Manage Social Media',
        to:'web-master/manage-social-media',
        Type: 74,
        UseForList:true,
    },
    {   label:'Manage Common Setting',
        to:'web-master/manage-common-setting',
        Type: 75,
        UseForList:true,
    },
    
    {   label:'Coupon Log',
        to:'reports/coupon-log',
        Type: 76,
        UseForList:true,
    },
]


export class MenuItems {
    getAll():IMenuItem[]{
        return data
    }
}